#!/bin/sh

if [ -n "$nv.boot.default" ]; then
	exit
fi

if [ $bootsource = mmc ]; then
	global.boot.default="bootchooser net"
elif [ $bootsource = net ]; then
	global.boot.default="net bootchooser"
else
	global.boot.default="disk0.1 net"
fi
