#!/bin/sh

if [ -n "${nv.boot.default}" ]; then
	exit
fi


if [ "$bootsource" = mmc ]; then
	detect mmc$bootsource_instance
	global.boot.default="mmc$bootsource_instance net"
fi

if [ "${global.model}" = "Radxa ROCK3 Model A" ]; then
	if [ "$bootsource" = "spi-nor" ]; then
		usbgadget -A '/dev/mmc1(sd)'
		global.autoboot=abort
	fi
fi
