#!/bin/sh

if [ -n "$nv.boot.default" ]; then
	exit
fi

if [ $bootsource = mmc ]; then
	detect mmc$bootsource_instance
	global.boot.default="bootchooser net"
else
	global.boot.default="net bootchooser"
fi

