#!/bin/sh

if [ -n "$nv.boot.default" ]; then
	exit
fi


if [ $bootsource = mmc ]; then
	detect mmc$bootsource_instance
	global.boot.default="mmc$bootsource_instance net"
else
	global.boot.default="net mmc1 mmc2 mmc3"
fi
